apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redguard.fullname" . }}
  labels:
    {{- include "redguard.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      {{- include "redguard.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        {{- include "redguard.selectorLabels" . | nindent 8 }}
        control-plane: controller-manager
    spec:
      serviceAccountName: {{ include "redguard.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: {{ .Values.operator.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.operator.securityContext.runAsUser }}
      containers:
      - name: manager
        image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
        command:
        - /manager
        args:
        - --leader-elect
        {{- if .Values.metrics.enabled }}
        - --metrics-bind-address=:{{ .Values.metrics.port }}
        {{- end }}
        - --health-probe-bind-address=:{{ .Values.health.port }}
        securityContext:
          allowPrivilegeEscalation: {{ .Values.operator.securityContext.allowPrivilegeEscalation }}
          capabilities:
            drop:
            {{- toYaml .Values.operator.securityContext.capabilities.drop | nindent 12 }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.health.port }}
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ .Values.health.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.operator.resources | nindent 10 }}
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
