apiVersion: v1
entries:
  redguard:
  - apiVersion: v2
    appVersion: 0.2.1
    created: "2026-01-14T11:25:19.845508+03:00"
    description: A Kubernetes operator for Redis with Sentinel for high availability
    digest: df43375c1dbadc66d929789ee7612c4a6cef594ba57dd66147061932acbe92c9
    home: https://github.com/redguard/redguard
    keywords:
    - redis
    - sentinel
    - operator
    - high-availability
    maintainers:
    - name: redguard
    name: redguard
    sources:
    - https://github.com/redguard/redguard
    type: application
    urls:
    - https://bcfmtolgahan.github.io/redis-operator/redguard-0.2.1.tgz
    version: 0.2.1
generated: "2026-01-14T11:25:19.844618+03:00"
